### ISSUE TITLE
Looking for production examples using the PHP SDK (Laravel)

### ISSUE THREAD

**Issue by jschwarzwalder** [awsdocs/aws-php-developers-guide#1]
Do you use the PHP SDK with [Laravel](https://laravel.com/)?

We are looking for examples for successfully integrating the PHP SDK to a Laravel Application.

**Comment by jschwarzwalder** [comment]
We are interested in an article that demonstrates best practices for adding and using the AWS SDK for PHP with Larvel.

1. Tips for installing the SDK and adding to a Larvel project.

2. Tips for configuring SDK credentials within the Larval framework.

3. Using Larvel and AWS SDK for PHP to create an S3 bucket, or send an object to an existing bucket.

4. Other simple examples that demonstrate how to use Larvel and AWS SDK for PHP together.

**Comment by pccornel** [comment]
Closing this issue as it has been open since last October, and we have received feedback on it. 

Paul
AWS Documentation
