### ISSUE TITLE
AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY

### ISSUE THREAD

**Issue by mmatyi** [awsdocs/aws-php-developers-guide#100]
in the file [aws-php-developers-guide](https://github.com/awsdocs/aws-php-developers-guide)/[doc_source](https://github.com/awsdocs/aws-php-developers-guide/tree/main/doc_source)/guide_credentials_environment.md once you mention AWS_SECRET_ACCESS_KEY but later for the Elastic beanstalk it is only AWS_SECRET_KEY without the ACCESS part. are they different or by mistake the ACCESS was omitted?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
