### ISSUE TITLE
AWS Code Samples

### ISSUE THREAD

**Issue by jschwarzwalder** [awsdocs/aws-php-developers-guide#15]
If you have ideas about any code samples for AWS Services that I should include in our [AWS SDK for PHP Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html), please let me know! 

Better yet, add your own code samples in the  [awsdocs/aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples) repo, and add an article here with instructions for how to use the Service.
Submit a pull request as explained in [these directions](../blob/master/CONTRIBUTING.md).

I look forward to hearing from you.

**Comment by swastikbanerjee07** [comment]
@jschwarzwalder  I had developed a chatbot using AWS's Amazon Lex api and had used Amazon Lambda function where I wrote the code.
Can I add that sample code here? But it's no way related to PHP :/

**Comment by jschwarzwalder** [comment]
You are correct, the code sample you described would not fit well into the php developer guide. 

However you can add code samples to the [Aws Doc SDK examples](https://github.com/awsdocs/aws-doc-sdk-examples). That repo contains examples in many languages. Most of the samples are small and demonstrate performing a single action.

I encourage you to check out that repo and see if there is anything that you can add.

Thank you for your interest in contributing.

**Comment by smartyshre** [comment]
@jschwarzwalder I developed a code that gets data from a MySQL database, hosted on AWS EC2 and then outputs the data on a webpage that is also hosted on the EC2 instance. The code outputs the data in JSON format so it is easy to retrieve the data from MySQL into a mobile application. Please let me know if that would be useful to add the sample code to this and the [AWS SDK for PHP Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html). Thank you!

**Comment by jschwarzwalder** [comment]
That sounds like it can be very useful.

Make a new issue with a proposed outline and we can figure out how best to include it.
