### ISSUE TITLE
PHP code to output JSON from MySQL

### ISSUE THREAD

**Issue by smartyshre** [awsdocs/aws-php-developers-guide#23]
@jschwarzwalder I developed a code that gets data from a MySQL database, hosted on AWS EC2 and then outputs the data on a webpage that is also hosted on the EC2 instance. The code outputs the data in JSON format so it is easy to retrieve the data from MySQL into a mobile application. Please let me know if that would be useful to add the sample code to this and the AWS SDK for PHP Developer Guide. Thank you!

**Comment by jschwarzwalder** [comment]
I'm going to close this issue.

Please reopen if you need further assistance.
