### ISSUE TITLE
Cognito Identity

### ISSUE THREAD

**Issue by Saphyel** [awsdocs/aws-php-developers-guide#3]
Seems like this section is gone... any chance to bring it back?

**Comment by jschwarzwalder** [comment]
After some investigating, I've not been able to find any previous article about using Cognito with PHP v3, but I did find the information about the Cognito client in our API documentation at https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-identity-2014-06-30.html

I also uncovered an article about using Cognito from the SDK for PHP version 2. 
I this the article you felt was missing? https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-cognitoidentity.html 

@Saphyel Can you be specific about what use case you looking to be documented? 

Do you simply want an example of how to use a client, or is there more that you were expecting. 

Thank you for clarifying.

**Comment by Saphyel** [comment]
@jschwarzwalder thanks for the link but the details of that documentation is the same like looking to the SDK... So I was expecting more like a guide with the typical commands that you are going to execute.. like sign up, login, get authorisation to do something, etc...

**Comment by jschwarzwalder** [comment]
Cognito has six scenarios for using Amazon Cognito listed in the Cognito Docs: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html

Is there a specific scenario you are looking for support on using the SDK for PHP to complete?

**Comment by Saphyel** [comment]
yes @jschwarzwalder I was looking for something similar to this: https://github.com/awslabs/aws-serverless-auth-reference-app but with the PHP sdk

**Comment by jschwarzwalder** [comment]
Are you wanting to use aws credentials on an identity pool or user pools?

https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html

**Comment by jschwarzwalder** [comment]
@Saphyel I am going to close this Issue since it is not clear what content is specifically requested. 

If you'd like to clarify, please create a new issue and reference this one. 

Thank you for your feedback.
