### ISSUE TITLE
Instantiation for all PHP on server

### ISSUE THREAD

**Issue by jasonabradley** [awsdocs/aws-php-developers-guide#34]
It would be good in Step 1 to identify how to call the instantiation for the PHP install on a server at a global level so all PHP is using it across the server.

**Comment by jschwarzwalder** [comment]
Thank you for your feedback @jasonabradley 

Is your request to add a section to installation or something more specific?

Please clarify if this is specific to AWS server (EC2) or broader.

**Comment by jasonabradley** [comment]
service_dynamodb-session-handler.rst 

In Step 1, for Registering the Sessions Handler, I was suggesting adding _where_ it could/should be added, particularly if it should work across an entire PHP installation.

**Comment by jschwarzwalder** [comment]
Thank you for clarifying.

**Comment by pccornel** [comment]
Thanks for your request. I will add it to the team’s list for future consideration and then close this issue accordingly. 

Paul
AWS Documentation
